/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutTeacherLayoutImport } from './routes/_layout/_teacher-layout'
import { Route as LayoutAuthLayoutImport } from './routes/_layout/_auth-layout'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const LayoutAuthLayoutAuthTeacherRegisterLazyImport = createFileRoute(
  '/_layout/_auth-layout/auth/teacher/register',
)()
const LayoutAuthLayoutAuthTeacherLoginLazyImport = createFileRoute(
  '/_layout/_auth-layout/auth/teacher/login',
)()
const LayoutAuthLayoutAuthStudentRegisterLazyImport = createFileRoute(
  '/_layout/_auth-layout/auth/student/register',
)()
const LayoutAuthLayoutAuthStudentLoginLazyImport = createFileRoute(
  '/_layout/_auth-layout/auth/student/login',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutTeacherLayoutRoute = LayoutTeacherLayoutImport.update({
  id: '/_layout/_teacher-layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthLayoutRoute = LayoutAuthLayoutImport.update({
  id: '/_layout/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthLayoutAuthTeacherRegisterLazyRoute =
  LayoutAuthLayoutAuthTeacherRegisterLazyImport.update({
    path: '/auth/teacher/register',
    getParentRoute: () => LayoutAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_auth-layout/auth/teacher/register.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthLayoutAuthTeacherLoginLazyRoute =
  LayoutAuthLayoutAuthTeacherLoginLazyImport.update({
    path: '/auth/teacher/login',
    getParentRoute: () => LayoutAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_auth-layout/auth/teacher/login.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthLayoutAuthStudentRegisterLazyRoute =
  LayoutAuthLayoutAuthStudentRegisterLazyImport.update({
    path: '/auth/student/register',
    getParentRoute: () => LayoutAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_auth-layout/auth/student/register.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthLayoutAuthStudentLoginLazyRoute =
  LayoutAuthLayoutAuthStudentLoginLazyImport.update({
    path: '/auth/student/login',
    getParentRoute: () => LayoutAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_auth-layout/auth/student/login.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth-layout': {
      preLoaderRoute: typeof LayoutAuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_teacher-layout': {
      preLoaderRoute: typeof LayoutTeacherLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth-layout/auth/student/login': {
      preLoaderRoute: typeof LayoutAuthLayoutAuthStudentLoginLazyImport
      parentRoute: typeof LayoutAuthLayoutImport
    }
    '/_layout/_auth-layout/auth/student/register': {
      preLoaderRoute: typeof LayoutAuthLayoutAuthStudentRegisterLazyImport
      parentRoute: typeof LayoutAuthLayoutImport
    }
    '/_layout/_auth-layout/auth/teacher/login': {
      preLoaderRoute: typeof LayoutAuthLayoutAuthTeacherLoginLazyImport
      parentRoute: typeof LayoutAuthLayoutImport
    }
    '/_layout/_auth-layout/auth/teacher/register': {
      preLoaderRoute: typeof LayoutAuthLayoutAuthTeacherRegisterLazyImport
      parentRoute: typeof LayoutAuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  LayoutAuthLayoutRoute.addChildren([
    LayoutAuthLayoutAuthStudentLoginLazyRoute,
    LayoutAuthLayoutAuthStudentRegisterLazyRoute,
    LayoutAuthLayoutAuthTeacherLoginLazyRoute,
    LayoutAuthLayoutAuthTeacherRegisterLazyRoute,
  ]),
  LayoutTeacherLayoutRoute,
])

/* prettier-ignore-end */
